environment:
  matrix:
    - PYTHON: "C:\\Python34"

install:
  - set PATH=%PYTHON%;%PATH%
  - python --version
  - python -m pip install -r test-requirements.txt

build: false  # Not a C# project.

test_script:
  - python -m pytest --cov=memaccess --cov-report term-missing
